# Generated by Django 5.2.3 on 2025-07-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé')], default='pending', help_text='Statut du paiement', max_length=10),
        ),
    ]
