# Generated by Django 5.2.3 on 2025-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='performance',
            field=models.CharField(blank=True, choices=[('jiddan', 'جيد جداً'), ('hassan', 'حسن'), ('la baas', 'لا بأس به'), ('mutawassit', 'متوسط'), ('daif', 'ضعيف')], max_length=20, null=True, verbose_name='التقييم'),
        ),
    ]
