# Generated by Django 5.2.3 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_progress_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='performance',
            field=models.CharField(blank=True, choices=[('ضعيف', 'ضعيف'), ('متوسط', 'متوسط'), ('جيد', 'جيد'), ('جيد جدًا', 'جيد جدًا'), ('ممتاز', 'ممتاز')], max_length=20, null=True, verbose_name='التقييم'),
        ),
    ]
